// flow-typed signature: 7abcecdfad541450e9b56a0b4a26257f
// flow-typed version: <<STUB>>/@types/node_v^17.0.16/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
