// flow-typed signature: 5808348cbe75a8dc4c3faac0fa433e0f
// flow-typed version: <<STUB>>/@types/react-dom_v^17.0.11/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
